apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: null
  labels:
    app: connect-worker
  name: connect-worker
spec:
  serviceName: "kafka-connect"
  replicas: 1
  selector:
    matchLabels:
      app: connect-worker
  template:
    metadata:
      labels:
        app: connect-worker
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - image: dwijad/kafka-connect:latest
        name: kafka-connect
        env:
        - name: BOOTSTRAP_SERVERS
          value: "test-kafka.default.svc.cluster.local:9092"
        - name: SASL_USER
          value: "user1"
        - name: SECURITY_PROTOCOL
          value: "PLAINTEXT"
        - name: SASL_PASSWORD
          value: "password"
        - name: LISTENER_PORT
          value: "8081"
        - name: REST_ADVERTISED_LISTENER
          value: "http"
        - name: SCHEMA_REGISTRY_URL
          value: "https://sr-service-https.default.svc:8082"
        - name: KEY_CONVERTER_SCHEMA_REGISTRY_URL
          value: "https://sr-service-https.default.svc:8082"
        - name: VALUE_CONVERTER_SCHEMA_REGISTRY_URL
          value: "https://sr-service-https.default.svc:8082"
        - name: KAFKA_JMX_PORT
          value: "8080"
        - name: KAFKA_JMX_OPTS
          value: "-Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.rmi.port=8080 -Djava.rmi.server.hostname=$(KAFKA_JMX_HOSTNAME) -javaagent:/u01/cnfkfk/etc/kafka/jmx_prometheus_javaagent-0.20.0.jar=8080:/u01/cnfkfk/etc/kafka/kafka-connect.yml"
        - name: KAFKA_JMX_HOSTNAME
          value: "connect-worker-1"
        - name: BROKER_LISTENER_MODE
          value: "PLAINTEXT"
        - name: SCHEMA_REGISTRY_MODE
          value: "HTTPS"
        resources:
          requests:
            memory: "1Gi"
            cpu: "0.5"
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 25
          periodSeconds: 5
#      imagePullSecrets:
#        - name: regcred
